// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"order-service/internal/adapter/repository/postgres"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockRepository
func (_mock *MockRepository) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockRepository_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Close() *MockRepository_Close_Call {
	return &MockRepository_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockRepository_Close_Call) Run(run func()) *MockRepository_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Close_Call) Return(err error) *MockRepository_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Close_Call) RunAndReturn(run func() error) *MockRepository_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Postgres provides a mock function for the type MockRepository
func (_mock *MockRepository) Postgres() postgresrepository.PostgresRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Postgres")
	}

	var r0 postgresrepository.PostgresRepository
	if returnFunc, ok := ret.Get(0).(func() postgresrepository.PostgresRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(postgresrepository.PostgresRepository)
		}
	}
	return r0
}

// MockRepository_Postgres_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Postgres'
type MockRepository_Postgres_Call struct {
	*mock.Call
}

// Postgres is a helper method to define mock.On call
func (_e *MockRepository_Expecter) Postgres() *MockRepository_Postgres_Call {
	return &MockRepository_Postgres_Call{Call: _e.mock.On("Postgres")}
}

func (_c *MockRepository_Postgres_Call) Run(run func()) *MockRepository_Postgres_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_Postgres_Call) Return(postgresRepository postgresrepository.PostgresRepository) *MockRepository_Postgres_Call {
	_c.Call.Return(postgresRepository)
	return _c
}

func (_c *MockRepository_Postgres_Call) RunAndReturn(run func() postgresrepository.PostgresRepository) *MockRepository_Postgres_Call {
	_c.Call.Return(run)
	return _c
}
