// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"order-service/config"
	"order-service/internal/adapter/repository/postgres"

	mock "github.com/stretchr/testify/mock"
	"github.com/uptrace/bun"
)

// NewMockPostgresRepository creates a new instance of MockPostgresRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostgresRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostgresRepository {
	mock := &MockPostgresRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostgresRepository is an autogenerated mock type for the PostgresRepository type
type MockPostgresRepository struct {
	mock.Mock
}

type MockPostgresRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostgresRepository) EXPECT() *MockPostgresRepository_Expecter {
	return &MockPostgresRepository_Expecter{mock: &_m.Mock}
}

// Atomic provides a mock function for the type MockPostgresRepository
func (_mock *MockPostgresRepository) Atomic(ctx context.Context, config1 *config.Config, fn postgresrepository.RepositoryAtomicCallback) error {
	ret := _mock.Called(ctx, config1, fn)

	if len(ret) == 0 {
		panic("no return value specified for Atomic")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *config.Config, postgresrepository.RepositoryAtomicCallback) error); ok {
		r0 = returnFunc(ctx, config1, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostgresRepository_Atomic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Atomic'
type MockPostgresRepository_Atomic_Call struct {
	*mock.Call
}

// Atomic is a helper method to define mock.On call
//   - ctx context.Context
//   - config1 *config.Config
//   - fn postgresrepository.RepositoryAtomicCallback
func (_e *MockPostgresRepository_Expecter) Atomic(ctx interface{}, config1 interface{}, fn interface{}) *MockPostgresRepository_Atomic_Call {
	return &MockPostgresRepository_Atomic_Call{Call: _e.mock.On("Atomic", ctx, config1, fn)}
}

func (_c *MockPostgresRepository_Atomic_Call) Run(run func(ctx context.Context, config1 *config.Config, fn postgresrepository.RepositoryAtomicCallback)) *MockPostgresRepository_Atomic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *config.Config
		if args[1] != nil {
			arg1 = args[1].(*config.Config)
		}
		var arg2 postgresrepository.RepositoryAtomicCallback
		if args[2] != nil {
			arg2 = args[2].(postgresrepository.RepositoryAtomicCallback)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPostgresRepository_Atomic_Call) Return(err error) *MockPostgresRepository_Atomic_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostgresRepository_Atomic_Call) RunAndReturn(run func(ctx context.Context, config1 *config.Config, fn postgresrepository.RepositoryAtomicCallback) error) *MockPostgresRepository_Atomic_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockPostgresRepository
func (_mock *MockPostgresRepository) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostgresRepository_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockPostgresRepository_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockPostgresRepository_Expecter) Close() *MockPostgresRepository_Close_Call {
	return &MockPostgresRepository_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockPostgresRepository_Close_Call) Run(run func()) *MockPostgresRepository_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPostgresRepository_Close_Call) Return(err error) *MockPostgresRepository_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostgresRepository_Close_Call) RunAndReturn(run func() error) *MockPostgresRepository_Close_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockPostgresRepository
func (_mock *MockPostgresRepository) DB() *bun.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *bun.DB
	if returnFunc, ok := ret.Get(0).(func() *bun.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bun.DB)
		}
	}
	return r0
}

// MockPostgresRepository_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockPostgresRepository_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockPostgresRepository_Expecter) DB() *MockPostgresRepository_DB_Call {
	return &MockPostgresRepository_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockPostgresRepository_DB_Call) Run(run func()) *MockPostgresRepository_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPostgresRepository_DB_Call) Return(dB *bun.DB) *MockPostgresRepository_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockPostgresRepository_DB_Call) RunAndReturn(run func() *bun.DB) *MockPostgresRepository_DB_Call {
	_c.Call.Return(run)
	return _c
}

// Order provides a mock function for the type MockPostgresRepository
func (_mock *MockPostgresRepository) Order() postgresrepository.OrderRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Order")
	}

	var r0 postgresrepository.OrderRepository
	if returnFunc, ok := ret.Get(0).(func() postgresrepository.OrderRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(postgresrepository.OrderRepository)
		}
	}
	return r0
}

// MockPostgresRepository_Order_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Order'
type MockPostgresRepository_Order_Call struct {
	*mock.Call
}

// Order is a helper method to define mock.On call
func (_e *MockPostgresRepository_Expecter) Order() *MockPostgresRepository_Order_Call {
	return &MockPostgresRepository_Order_Call{Call: _e.mock.On("Order")}
}

func (_c *MockPostgresRepository_Order_Call) Run(run func()) *MockPostgresRepository_Order_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPostgresRepository_Order_Call) Return(orderRepository postgresrepository.OrderRepository) *MockPostgresRepository_Order_Call {
	_c.Call.Return(orderRepository)
	return _c
}

func (_c *MockPostgresRepository_Order_Call) RunAndReturn(run func() postgresrepository.OrderRepository) *MockPostgresRepository_Order_Call {
	_c.Call.Return(run)
	return _c
}
