// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"order-service/internal/adapter/repository/postgres"
	"order-service/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Create(ctx context.Context, order *entity.Order) (*entity.Order, error) {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Order) (*entity.Order, error)); ok {
		return returnFunc(ctx, order)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Order) *entity.Order); ok {
		r0 = returnFunc(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Order) error); ok {
		r1 = returnFunc(ctx, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - order *entity.Order
func (_e *MockOrderRepository_Expecter) Create(ctx interface{}, order interface{}) *MockOrderRepository_Create_Call {
	return &MockOrderRepository_Create_Call{Call: _e.mock.On("Create", ctx, order)}
}

func (_c *MockOrderRepository_Create_Call) Run(run func(ctx context.Context, order *entity.Order)) *MockOrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Order
		if args[1] != nil {
			arg1 = args[1].(*entity.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Create_Call) Return(order1 *entity.Order, err error) *MockOrderRepository_Create_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *MockOrderRepository_Create_Call) RunAndReturn(run func(ctx context.Context, order *entity.Order) (*entity.Order, error)) *MockOrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Delete(ctx context.Context, id uint32) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockOrderRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint32
func (_e *MockOrderRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockOrderRepository_Delete_Call {
	return &MockOrderRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockOrderRepository_Delete_Call) Run(run func(ctx context.Context, id uint32)) *MockOrderRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Delete_Call) Return(err error) *MockOrderRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uint32) error) *MockOrderRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Find(ctx context.Context, filter *postgresrepository.FilterOrderPayload) ([]*entity.Order, int, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []*entity.Order
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *postgresrepository.FilterOrderPayload) ([]*entity.Order, int, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *postgresrepository.FilterOrderPayload) []*entity.Order); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *postgresrepository.FilterOrderPayload) int); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, *postgresrepository.FilterOrderPayload) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockOrderRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockOrderRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *postgresrepository.FilterOrderPayload
func (_e *MockOrderRepository_Expecter) Find(ctx interface{}, filter interface{}) *MockOrderRepository_Find_Call {
	return &MockOrderRepository_Find_Call{Call: _e.mock.On("Find", ctx, filter)}
}

func (_c *MockOrderRepository_Find_Call) Run(run func(ctx context.Context, filter *postgresrepository.FilterOrderPayload)) *MockOrderRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *postgresrepository.FilterOrderPayload
		if args[1] != nil {
			arg1 = args[1].(*postgresrepository.FilterOrderPayload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Find_Call) Return(orders []*entity.Order, n int, err error) *MockOrderRepository_Find_Call {
	_c.Call.Return(orders, n, err)
	return _c
}

func (_c *MockOrderRepository_Find_Call) RunAndReturn(run func(ctx context.Context, filter *postgresrepository.FilterOrderPayload) ([]*entity.Order, int, error)) *MockOrderRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) FindByID(ctx context.Context, id uint32) (*entity.Order, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *entity.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) (*entity.Order, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) *entity.Order); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockOrderRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint32
func (_e *MockOrderRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockOrderRepository_FindByID_Call {
	return &MockOrderRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockOrderRepository_FindByID_Call) Run(run func(ctx context.Context, id uint32)) *MockOrderRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_FindByID_Call) Return(order *entity.Order, err error) *MockOrderRepository_FindByID_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uint32) (*entity.Order, error)) *MockOrderRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Update(ctx context.Context, order *entity.Order) (*entity.Order, error) {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Order) (*entity.Order, error)); ok {
		return returnFunc(ctx, order)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Order) *entity.Order); ok {
		r0 = returnFunc(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Order) error); ok {
		r1 = returnFunc(ctx, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockOrderRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - order *entity.Order
func (_e *MockOrderRepository_Expecter) Update(ctx interface{}, order interface{}) *MockOrderRepository_Update_Call {
	return &MockOrderRepository_Update_Call{Call: _e.mock.On("Update", ctx, order)}
}

func (_c *MockOrderRepository_Update_Call) Run(run func(ctx context.Context, order *entity.Order)) *MockOrderRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Order
		if args[1] != nil {
			arg1 = args[1].(*entity.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Update_Call) Return(order1 *entity.Order, err error) *MockOrderRepository_Update_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *MockOrderRepository_Update_Call) RunAndReturn(run func(ctx context.Context, order *entity.Order) (*entity.Order, error)) *MockOrderRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) UpdateStatus(ctx context.Context, id uint32, status string) error {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32, string) error); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockOrderRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint32
//   - status string
func (_e *MockOrderRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}) *MockOrderRepository_UpdateStatus_Call {
	return &MockOrderRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockOrderRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id uint32, status string)) *MockOrderRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderRepository_UpdateStatus_Call) Return(err error) *MockOrderRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, id uint32, status string) error) *MockOrderRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
