// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"order-service/proto/pb"

	"github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

// NewMockInventoryServiceClient creates a new instance of MockInventoryServiceClient.
func NewMockInventoryServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInventoryServiceClient {
	mock := &MockInventoryServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInventoryServiceClient is an autogenerated mock type for the InventoryServiceClient type
type MockInventoryServiceClient struct {
	mock.Mock
}

type MockInventoryServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInventoryServiceClient) EXPECT() *MockInventoryServiceClient_Expecter {
	return &MockInventoryServiceClient_Expecter{mock: &_m.Mock}
}

func (_mock *MockInventoryServiceClient) GetProduct(ctx context.Context, in *pb.GetProductRequest, opts ...grpc.CallOption) (*pb.Product, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 *pb.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.GetProductRequest, ...grpc.CallOption) (*pb.Product, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.GetProductRequest, ...grpc.CallOption) *pb.Product); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pb.GetProductRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockInventoryServiceClient_GetProduct_Call struct {
	*mock.Call
}

func (_e *MockInventoryServiceClient_Expecter) GetProduct(ctx interface{}, in interface{}, opts ...interface{}) *MockInventoryServiceClient_GetProduct_Call {
	return &MockInventoryServiceClient_GetProduct_Call{Call: _e.mock.On("GetProduct", append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockInventoryServiceClient_GetProduct_Call) Run(run func(ctx context.Context, in *pb.GetProductRequest, opts ...grpc.CallOption)) *MockInventoryServiceClient_GetProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		varargs := make([]grpc.CallOption, len(args)-2)
		for i, arg := range args[2:] {
			varargs[i] = arg.(grpc.CallOption)
		}
		run(args[0].(context.Context), args[1].(*pb.GetProductRequest), varargs...)
	})
	return _c
}

func (_c *MockInventoryServiceClient_GetProduct_Call) Return(_a0 *pb.Product, _a1 error) *MockInventoryServiceClient_GetProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryServiceClient_GetProduct_Call) RunAndReturn(run func(context.Context, *pb.GetProductRequest, ...grpc.CallOption) (*pb.Product, error)) *MockInventoryServiceClient_GetProduct_Call {
	_c.Call.Return(run)
	return _c
}

func (_mock *MockInventoryServiceClient) CreateProduct(ctx context.Context, in *pb.CreateProductRequest, opts ...grpc.CallOption) (*pb.Product, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 *pb.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.CreateProductRequest, ...grpc.CallOption) (*pb.Product, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.CreateProductRequest, ...grpc.CallOption) *pb.Product); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pb.CreateProductRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockInventoryServiceClient_CreateProduct_Call struct {
	*mock.Call
}

func (_e *MockInventoryServiceClient_Expecter) CreateProduct(ctx interface{}, in interface{}, opts ...interface{}) *MockInventoryServiceClient_CreateProduct_Call {
	return &MockInventoryServiceClient_CreateProduct_Call{Call: _e.mock.On("CreateProduct", append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockInventoryServiceClient_CreateProduct_Call) Run(run func(ctx context.Context, in *pb.CreateProductRequest, opts ...grpc.CallOption)) *MockInventoryServiceClient_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		varargs := make([]grpc.CallOption, len(args)-2)
		for i, arg := range args[2:] {
			varargs[i] = arg.(grpc.CallOption)
		}
		run(args[0].(context.Context), args[1].(*pb.CreateProductRequest), varargs...)
	})
	return _c
}

func (_c *MockInventoryServiceClient_CreateProduct_Call) Return(_a0 *pb.Product, _a1 error) *MockInventoryServiceClient_CreateProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryServiceClient_CreateProduct_Call) RunAndReturn(run func(context.Context, *pb.CreateProductRequest, ...grpc.CallOption) (*pb.Product, error)) *MockInventoryServiceClient_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

func (_mock *MockInventoryServiceClient) UpdateProduct(ctx context.Context, in *pb.UpdateProductRequest, opts ...grpc.CallOption) (*pb.Product, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 *pb.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.UpdateProductRequest, ...grpc.CallOption) (*pb.Product, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.UpdateProductRequest, ...grpc.CallOption) *pb.Product); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pb.UpdateProductRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockInventoryServiceClient_UpdateProduct_Call struct {
	*mock.Call
}

func (_e *MockInventoryServiceClient_Expecter) UpdateProduct(ctx interface{}, in interface{}, opts ...interface{}) *MockInventoryServiceClient_UpdateProduct_Call {
	return &MockInventoryServiceClient_UpdateProduct_Call{Call: _e.mock.On("UpdateProduct", append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockInventoryServiceClient_UpdateProduct_Call) Run(run func(ctx context.Context, in *pb.UpdateProductRequest, opts ...grpc.CallOption)) *MockInventoryServiceClient_UpdateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		varargs := make([]grpc.CallOption, len(args)-2)
		for i, arg := range args[2:] {
			varargs[i] = arg.(grpc.CallOption)
		}
		run(args[0].(context.Context), args[1].(*pb.UpdateProductRequest), varargs...)
	})
	return _c
}

func (_c *MockInventoryServiceClient_UpdateProduct_Call) Return(_a0 *pb.Product, _a1 error) *MockInventoryServiceClient_UpdateProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryServiceClient_UpdateProduct_Call) RunAndReturn(run func(context.Context, *pb.UpdateProductRequest, ...grpc.CallOption) (*pb.Product, error)) *MockInventoryServiceClient_UpdateProduct_Call {
	_c.Call.Return(run)
	return _c
}

func (_mock *MockInventoryServiceClient) ListProducts(ctx context.Context, in *pb.ListProductsRequest, opts ...grpc.CallOption) (*pb.ListProductsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListProducts")
	}

	var r0 *pb.ListProductsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.ListProductsRequest, ...grpc.CallOption) (*pb.ListProductsResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.ListProductsRequest, ...grpc.CallOption) *pb.ListProductsResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.ListProductsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pb.ListProductsRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockInventoryServiceClient_ListProducts_Call struct {
	*mock.Call
}

func (_e *MockInventoryServiceClient_Expecter) ListProducts(ctx interface{}, in interface{}, opts ...interface{}) *MockInventoryServiceClient_ListProducts_Call {
	return &MockInventoryServiceClient_ListProducts_Call{Call: _e.mock.On("ListProducts", append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockInventoryServiceClient_ListProducts_Call) Run(run func(ctx context.Context, in *pb.ListProductsRequest, opts ...grpc.CallOption)) *MockInventoryServiceClient_ListProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		varargs := make([]grpc.CallOption, len(args)-2)
		for i, arg := range args[2:] {
			varargs[i] = arg.(grpc.CallOption)
		}
		run(args[0].(context.Context), args[1].(*pb.ListProductsRequest), varargs...)
	})
	return _c
}

func (_c *MockInventoryServiceClient_ListProducts_Call) Return(_a0 *pb.ListProductsResponse, _a1 error) *MockInventoryServiceClient_ListProducts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryServiceClient_ListProducts_Call) RunAndReturn(run func(context.Context, *pb.ListProductsRequest, ...grpc.CallOption) (*pb.ListProductsResponse, error)) *MockInventoryServiceClient_ListProducts_Call {
	_c.Call.Return(run)
	return _c
}

func (_mock *MockInventoryServiceClient) DeleteProduct(ctx context.Context, in *pb.DeleteProductRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 *emptypb.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.DeleteProductRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.DeleteProductRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pb.DeleteProductRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockInventoryServiceClient_DeleteProduct_Call struct {
	*mock.Call
}

func (_e *MockInventoryServiceClient_Expecter) DeleteProduct(ctx interface{}, in interface{}, opts ...interface{}) *MockInventoryServiceClient_DeleteProduct_Call {
	return &MockInventoryServiceClient_DeleteProduct_Call{Call: _e.mock.On("DeleteProduct", append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockInventoryServiceClient_DeleteProduct_Call) Run(run func(ctx context.Context, in *pb.DeleteProductRequest, opts ...grpc.CallOption)) *MockInventoryServiceClient_DeleteProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		varargs := make([]grpc.CallOption, len(args)-2)
		for i, arg := range args[2:] {
			varargs[i] = arg.(grpc.CallOption)
		}
		run(args[0].(context.Context), args[1].(*pb.DeleteProductRequest), varargs...)
	})
	return _c
}

func (_c *MockInventoryServiceClient_DeleteProduct_Call) Return(_a0 *emptypb.Empty, _a1 error) *MockInventoryServiceClient_DeleteProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryServiceClient_DeleteProduct_Call) RunAndReturn(run func(context.Context, *pb.DeleteProductRequest, ...grpc.CallOption) (*emptypb.Empty, error)) *MockInventoryServiceClient_DeleteProduct_Call {
	_c.Call.Return(run)
	return _c
}

func (_mock *MockInventoryServiceClient) ListReservations(ctx context.Context, in *pb.ListReservationsRequest, opts ...grpc.CallOption) (*pb.ListReservationsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListReservations")
	}

	var r0 *pb.ListReservationsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.ListReservationsRequest, ...grpc.CallOption) (*pb.ListReservationsResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.ListReservationsRequest, ...grpc.CallOption) *pb.ListReservationsResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.ListReservationsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pb.ListReservationsRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockListReservations_Call struct {
	*mock.Call
}

func (_e *MockInventoryServiceClient_Expecter) ListReservations(ctx interface{}, in interface{}, opts ...interface{}) *MockListReservations_Call {
	return &MockListReservations_Call{Call: _e.mock.On("ListReservations", append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockListReservations_Call) Run(run func(ctx context.Context, in *pb.ListReservationsRequest, opts ...grpc.CallOption)) *MockListReservations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		varargs := make([]grpc.CallOption, len(args)-2)
		for i, arg := range args[2:] {
			varargs[i] = arg.(grpc.CallOption)
		}
		run(args[0].(context.Context), args[1].(*pb.ListReservationsRequest), varargs...)
	})
	return _c
}

func (_c *MockListReservations_Call) Return(_a0 *pb.ListReservationsResponse, _a1 error) *MockListReservations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListReservations_Call) RunAndReturn(run func(context.Context, *pb.ListReservationsRequest, ...grpc.CallOption) (*pb.ListReservationsResponse, error)) *MockListReservations_Call {
	_c.Call.Return(run)
	return _c
}

func (_mock *MockInventoryServiceClient) GetReservation(ctx context.Context, in *pb.GetReservationRequest, opts ...grpc.CallOption) (*pb.Reservation, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetReservation")
	}

	var r0 *pb.Reservation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.GetReservationRequest, ...grpc.CallOption) (*pb.Reservation, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.GetReservationRequest, ...grpc.CallOption) *pb.Reservation); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.Reservation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pb.GetReservationRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockGetReservation_Call struct {
	*mock.Call
}

func (_e *MockInventoryServiceClient_Expecter) GetReservation(ctx interface{}, in interface{}, opts ...interface{}) *MockGetReservation_Call {
	return &MockGetReservation_Call{Call: _e.mock.On("GetReservation", append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockGetReservation_Call) Run(run func(ctx context.Context, in *pb.GetReservationRequest, opts ...grpc.CallOption)) *MockGetReservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		varargs := make([]grpc.CallOption, len(args)-2)
		for i, arg := range args[2:] {
			varargs[i] = arg.(grpc.CallOption)
		}
		run(args[0].(context.Context), args[1].(*pb.GetReservationRequest), varargs...)
	})
	return _c
}

func (_c *MockGetReservation_Call) Return(_a0 *pb.Reservation, _a1 error) *MockGetReservation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetReservation_Call) RunAndReturn(run func(context.Context, *pb.GetReservationRequest, ...grpc.CallOption) (*pb.Reservation, error)) *MockGetReservation_Call {
	_c.Call.Return(run)
	return _c
}

func (_mock *MockInventoryServiceClient) CreateReservation(ctx context.Context, in *pb.CreateReservationRequest, opts ...grpc.CallOption) (*pb.Reservation, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateReservation")
	}

	var r0 *pb.Reservation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.CreateReservationRequest, ...grpc.CallOption) (*pb.Reservation, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.CreateReservationRequest, ...grpc.CallOption) *pb.Reservation); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.Reservation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pb.CreateReservationRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockCreateReservation_Call struct {
	*mock.Call
}

func (_e *MockInventoryServiceClient_Expecter) CreateReservation(ctx interface{}, in interface{}, opts ...interface{}) *MockCreateReservation_Call {
	return &MockCreateReservation_Call{Call: _e.mock.On("CreateReservation", append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockCreateReservation_Call) Run(run func(ctx context.Context, in *pb.CreateReservationRequest, opts ...grpc.CallOption)) *MockCreateReservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		varargs := make([]grpc.CallOption, len(args)-2)
		for i, arg := range args[2:] {
			varargs[i] = arg.(grpc.CallOption)
		}
		run(args[0].(context.Context), args[1].(*pb.CreateReservationRequest), varargs...)
	})
	return _c
}

func (_c *MockCreateReservation_Call) Return(_a0 *pb.Reservation, _a1 error) *MockCreateReservation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreateReservation_Call) RunAndReturn(run func(context.Context, *pb.CreateReservationRequest, ...grpc.CallOption) (*pb.Reservation, error)) *MockCreateReservation_Call {
	_c.Call.Return(run)
	return _c
}

func (_mock *MockInventoryServiceClient) UpdateReservationStatus(ctx context.Context, in *pb.UpdateReservationStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReservationStatus")
	}

	var r0 *emptypb.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.UpdateReservationStatusRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pb.UpdateReservationStatusRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *pb.UpdateReservationStatusRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockInventoryServiceClient_UpdateReservationStatus_Call struct {
	*mock.Call
}

func (_e *MockInventoryServiceClient_Expecter) UpdateReservationStatus(ctx interface{}, in interface{}, opts ...interface{}) *MockInventoryServiceClient_UpdateReservationStatus_Call {
	return &MockInventoryServiceClient_UpdateReservationStatus_Call{Call: _e.mock.On("UpdateReservationStatus", append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockInventoryServiceClient_UpdateReservationStatus_Call) Run(run func(ctx context.Context, in *pb.UpdateReservationStatusRequest, opts ...grpc.CallOption)) *MockInventoryServiceClient_UpdateReservationStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		varargs := make([]grpc.CallOption, len(args)-2)
		for i, arg := range args[2:] {
			varargs[i] = arg.(grpc.CallOption)
		}
		run(args[0].(context.Context), args[1].(*pb.UpdateReservationStatusRequest), varargs...)
	})
	return _c
}

func (_c *MockInventoryServiceClient_UpdateReservationStatus_Call) Return(_a0 *emptypb.Empty, _a1 error) *MockInventoryServiceClient_UpdateReservationStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInventoryServiceClient_UpdateReservationStatus_Call) RunAndReturn(run func(context.Context, *pb.UpdateReservationStatusRequest, ...grpc.CallOption) (*emptypb.Empty, error)) *MockInventoryServiceClient_UpdateReservationStatus_Call {
	_c.Call.Return(run)
	return _c
}
